# Generated by Django 5.1.3 on 2025-02-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('flyId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre de vuelo')),
                ('type', models.CharField(choices=[('N', 'National'), ('I', 'International')], max_length=1, verbose_name='tipo de vuelo')),
                ('price', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
